apiVersion: apps/v1
kind: Deployment
metadata :
    name: phpmyadmin-dep
    labels:
        app: phpmy
spec:
    selector:
        matchLabels:
           app: phpmy
    template:
        metadata:
            name: phpmyadmin-pod
            labels:
             app: phpmy
        spec:
            restartPolicy: Always
            containers:
             - name: phpmyadmin
               imagePullPolicy: Never
               image: phpmyadmin
               ports:
                - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
    name: phpmyadmin-svc
spec:
    type: NodePort
    ports:
        - name: phpmyadmin
          port: 5000
          targetPort: 5000
          nodePort: 5000
    selector:
        app: phpmy