apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress-deployment
spec:
    replicas: 1
    selector:
            matchLabels:
                 app: wordp
    template:
            metadata:
                labels:
                   app: wordp
            spec:
                restartPolicy: Always
                containers:
                        - name: wordpress
                          imagePullPolicy: Never
                          image: wordpress:latest
                          ports:
                          - containerPort: 5050
                
---
apiVersion: v1
kind: Service
metadata:
    name: wordpress-service
spec:
    type: NodePort
    selector:
       app: wordp
    ports:
    - port: 5050
      targetPort: 5050
      nodePort: 5050